In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
k=[4,2.56789,9,87,9999,40,'hyderabad']

In [ ]:
k

[4, 2.56789, 9, 87, 9999, 40, 'hyderabad']

In [ ]:
pd.Series(k)

0            4
1      2.56789
2            9
3           87
4         9999
5           40
6    hyderabad
dtype: object

In [ ]:
a=np.random.randint(20,50,(5,4))

In [ ]:
a

array([[20, 49, 29, 23],
       [39, 37, 34, 30],
       [36, 31, 33, 26],
       [34, 26, 46, 49],
       [41, 24, 24, 26]])

In [ ]:
a=np.random.randint(20,50,15)

In [ ]:
a

array([20, 46, 48, 40, 21, 24, 42, 20, 33, 26, 22, 34, 45, 33, 23])

In [ ]:
pd.Series(a)

0     20
1     46
2     48
3     40
4     21
5     24
6     42
7     20
8     33
9     26
10    22
11    34
12    45
13    33
14    23
dtype: int64

In [ ]:
b=np.random.randint(100,200,(6,5))

In [ ]:
b.ndim

2

In [ ]:
b

array([[133, 171, 166, 193, 160],
       [187, 133, 146, 148, 176],
       [176, 191, 182, 197, 151],
       [174, 184, 136, 130, 136],
       [132, 151, 169, 182, 119],
       [177, 133, 109, 172, 156]])

In [ ]:


pd.DataFrame(b)




0    1    2    3    4
0  133  171  166  193  160
1  187  133  146  148  176
2  176  191  182  197  151
3  174  184  136  130  136
4  132  151  169  182  119
5  177  133  109  172  156

In [ ]:
df=pd.DataFrame(b,columns=['Roll','Name','age','adds','country'])

In [ ]:
df

Roll  Name  age  adds  country
0   133   171  166   193      160
1   187   133  146   148      176
2   176   191  182   197      151
3   174   184  136   130      136
4   132   151  169   182      119
5   177   133  109   172      156

In [ ]:
df=pd.DataFrame(b,columns=['Roll','Name','age','adds','country'],index=[182,184,185,186,188,189])

In [ ]:
df

Roll  Name  age  adds  country
182   133   171  166   193      160
184   187   133  146   148      176
185   176   191  182   197      151
186   174   184  136   130      136
188   132   151  169   182      119
189   177   133  109   172      156

In [ ]:
df.loc[186]

Roll       174
Name       184
age        136
adds       130
country    136
Name: 186, dtype: int64

In [ ]:
df.iloc[0]

Roll       133
Name       171
age        166
adds       193
country    160
Name: 182, dtype: int64

In [ ]:
df.iloc[0,0]

133

In [ ]:
df.iloc[0,0:3]

Roll    133
Name    171
age     166
Name: 182, dtype: int64

In [ ]:
df.iloc[0,[0,1,2]]

Roll    133
Name    171
age     166
Name: 182, dtype: int64

In [ ]:
df.iloc[[0,5]]

Roll  Name  age  adds  country
182   133   171  166   193      160
189   177   133  109   172      156

In [ ]:
df.iloc[[1,3, 4]]

Roll  Name  age  adds  country
184   187   133  146   148      176
186   174   184  136   130      136
188   132   151  169   182      119

In [ ]:
df.loc[[184,185,186]]

Roll  Name  age  adds  country
184   187   133  146   148      176
185   176   191  182   197      151
186   174   184  136   130      136

In [ ]:
df[['age','adds']]

age  adds
182  166   193
184  146   148
185  182   197
186  136   130
188  169   182
189  109   172

In [36]:
df[['age','adds','Roll']]

age  adds  Roll
182  166   193   133
184  146   148   187
185  182   197   176
186  136   130   174
188  169   182   132
189  109   172   177

In [38]:
df[['Name','country']]

Name  country
182   171      160
184   133      176
185   191      151
186   184      136
188   151      119
189   133      156

In [39]:
df.loc[[184,185,186],['Name','country']]

Name  country
184   133      176
185   191      151
186   184      136

In [40]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [42]:
n=sns.load_dataset('titanic')
n

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [43]:
type(n)

pandas.core.frame.DataFrame

In [45]:
n.shape

(891, 15)

In [46]:
n.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')