In [3]:
#Import pandas
import pandas as pd

In [2]:
d = [29,45,67,12,34]
series = pd.Series(d)
print(series)

0    29
1    45
2    67
3    12
4    34
dtype: int64


In [7]:
data = [1,2,3,4]
i = ['A','B','c','d']
series = pd.Series(data,index=i)
print(series)


A    1
B    2
c    3
d    4
dtype: int64


In [9]:
data = {'A':1,'B':2,'c':3,'d':4}
series = pd.Series(data)
print(series)


A    1
B    2
c    3
d    4
dtype: int64


In [10]:
series.replace(3,5)

A    1
B    2
c    5
d    4
dtype: int64

In [11]:
import numpy as np
data = np.array ([1,2,3,4])
i = ['A','B','c','d']
series = pd.Series(data,index=i)
print(series)


A    1
B    2
c    3
d    4
dtype: int32


In [13]:
data = {'name':['sahasra','sa','uuu'],'age':[20,40,50],'country':['india','africa','america']}
df = pd.DataFrame(data)
print(df)

      name  age  country
0  sahasra   20    india
1       sa   40   africa
2      uuu   50  america


In [16]:
import numpy as np
data = np.array ([[1,2,3,4],[4,5,6,7],[8,9,0,6]])
print(data)
df = pd.DataFrame(data)
print(df)


[[1 2 3 4]
 [4 5 6 7]
 [8 9 0 6]]
   0  1  2  3
0  1  2  3  4
1  4  5  6  7
2  8  9  0  6
